myproject2/inmakespro/movieproject/movieapp/urls.py
from django.urls import path
from.import views
app_name='movieapp'
urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'), #index.html
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
     path('delete/<int:id>/',views.delete,name='delete')
]

myproject2/inmakespro/movieproject/movieproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("movieapp.urls"))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject2/inmakespro/movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')
    def __str__(self):
        return self.name

myproject2/inmakespro/movieproject/movieapp/forms.py
from django import forms
from.models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','year','img']

myproject2/inmakespro/movieproject/movieapp/views.py
from django.shortcuts import render,HttpResponse,redirect
from . models import Movie
from . forms import MovieForm

# Create your views here.
def index(request):
    movie=Movie.objects.all()
    context={'movie_list':movie}
    return render(request,'index.html',context)
def detail(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    #return HttpResponse("this is movie no %s"% movie_id)
    return render(request,"detail.html",{'movie':movie})
def add_movie(request):
    if request.method=="POST":
        name=request.POST.get('name')
        desc=request.POST.get('desc')
        year=request.POST.get('year')
        img=request.FILES['img']
        movie=Movie(name=name,desc=desc,year=year,img=img)
        movie.save()
    return render(request,'add.html')
def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None, request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,"edit.html",{'form':form,'movie':movie})
def delete(request,id):
        if request.method=='POST':
             movie=Movie.objects.get(id=id)
             movie.delete()
             return redirect('/')
        return render(request,"delete.html")

myproject2/inmakespro/movieproject/templates/add.html
{% extends 'base.html' %} 
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
        <input type="text" name="name" placeholder="Enter u r movie name">
        <input type="text" name="desc" placeholder="Enter movie description">
        <input type="text" name="year" placeholder="Enter u r movie year">
        <input type="file" name="img" >
        <input type="Submit">
</form>
{% comment %} {% endfor %} {% endcomment %}
{% endblock %} 

myproject2/inmakespro/movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'style.css' %}">
  </head>
<body>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">ONLINE MOVIE</a>
      </div>
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
      </ul>
      <form class="navbar-form navbar-left" action="/action_page.php">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search" name="search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
        <button type="submit" class="btn btn-default">ADDING MOVIES</button>
      </form>
    </div>
  </nav>
{% block body %}
{% endblock %}
</body>
</html>

myproject2/inmakespro/movieproject/templates/delete.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    Are you sure u want to delete this movie?
    <input type="Submit">
</form>

myproject2/inmakespro/movieproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container"><!--61 st BOOTSTARP-->
    <div class="row">
        <div class="col-md-6">
            <img src = "{{movie.img.url}}" width="250" height="250">
        </div>
        <div class="col-md-6">
            <h1>{{movie.name}}</h1>
            <h6>{{movie.desc}}</h6>
            <h4>{{movie.year}}</h4>
            <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">update</a>
            <a class="btn btn-warning" href="{% url 'movieapp:delete' movie.id %}">delete</a>
        </div>
    </div>
</div>
{% endblock %}


<!-- <img src = "{{movie.img.url}}" width="100" height="100"> 
{{movie.name}}<br>
{{movie.desc}}<br>
{{movie.year}}
<a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">update</a>
<a class="btn btn-warning" href="{% url 'movieapp:delete' movie.id %}">delete</a>-->
{% comment %} {% endblock %}  {% endcomment %}

myproject2/inmakespro/movieproject/templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="Submit">
</form>

myproject2/inmakespro/movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container"> <!--60 VIDEO BOOTSTRAP-->
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3">
            <div class="card" style="width: 18rem;">
                <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" width="250px" height="250px">
                <div class="card-body">
                  <h1 class="card-title">{{i.name}}</h1>
                  <p class="card-text" align="justify" >{{i.desc}}</p>
                  <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">{{i.name}}<br></a>
                </div>
              </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

{% comment %} {% for i in movie_list %}
{% comment %} <a href = "movie/{{i.id}}">{{i.name}}<br> 
<a href = "{% url 'detail' i.id %}">{{i.name}}<br><!--urls.py detail-->{% endcomment %}
{% comment %} <img src = "{{i.img.url}}" width="100" height="100"> {% endcomment %} 
{% comment %} <a href = "{% url 'movieapp:detail' i.id %}">{{i.name}}<br> {% endcomment %}